### ISSUE TITLE
Client-Side Exception When Using the Back Button in Browser

### ISSUE THREAD

**Issue by yashtekavade** [harshsbhat/sealnotes#17]
Issue Description:
Problem:
While navigating the application, when I don't find the desired page or data and press the browser's "Back" button, the application throws the following error:

Application error: a client-side exception has occurred (see the browser console for more information).
Steps to Reproduce:
Open the application in the browser.
Navigate to any page that doesn't return the expected results or data.
Press the browser's "Back" button to navigate back.
Observe the client-side exception displayed.
Expected Behavior:
The application should return to the previous state or page without throwing an error.

Actual Behavior:
The application shows a blank page with the error message mentioned above.

![WhatsApp Image 2024-12-26 at 22 41 49_4ccf6763](https://github.com/user-attachments/assets/ddf3e7d9-a12f-403b-a8dc-300fed408463)

**Comment by harshsbhat** [comment]
Ah, I forgot about this one.  I did solve this error for other instances. Thanks for raising it @yashtekavade 

Are you giving it a go or should I?

**Comment by harshsbhat** [comment]
Merged the fix for this thank you once again!
